name: Chunky
main: com.dumptruckman.minecraft.chunky.bukkit.ChunkyPlugin
version: ${project.version}-b${build.number}
author: dumptruckman
depend: [WorldEdit]

commands:
  chunky:
    aliases: c